### ISSUE TITLE
could you share the dataset cropped_EHF/images.zip for downloading?

### ISSUE THREAD

**Issue by flydragon2018** [xiyichen/smplify-x-partial#2]
or the image format/requirements?

**Comment by xiyichen** [comment]
Hello, 
according to the license, I'm not allowed to redistribute the EHF images. The bounding boxes we used to cropped them (in the format of x_min, x_max, y_min, y_max) are provided in the folder "EHF_bbox" in [this zip file](https://polybox.ethz.ch/index.php/s/2Ii1wdb3Hei7aba). You can download the EHF dataset [here](https://smpl-x.is.tue.mpg.de/download.php) after a registration (under "EHF: Evaluation Dataset") and use the bounding boxes to get the same cropped images that we used.
